SELECT 
    C.HISTORY_ID,
    C.CAR_ID,
    DATE_FORMAT(C.START_DATE, '%Y-%m-%d') AS START_DATE,
    DATE_FORMAT(C.END_DATE, '%Y-%m-%d') AS END_DATE,
IF(DATEDIFF(C.END_DATE, C.START_DATE) >= 29, '장기 대여', '단기 대여') AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
WHERE C.START_DATE LIKE '2022-09%'
ORDER BY C.HISTORY_ID DESC;